version: '3.3'

services:
  redis:
    image: redis:7.2.1-alpine3.18
    environment:
      REDIS_PASSWORD: Redis@123
    ports:
      - '6379:6379'
    restart: on-failure
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD}"

  prometheus:
    image: prom/prometheus:v2.46.0
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana:10.0.3-ubuntu
    ports:
      - '3000:3000'
    volumes:
      - grafana:/var/lib/grafana
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
  mongodb:
    image: mongodb/mongodb-community-server:7.0.1-ubuntu2204
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mongo@123
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    restart: on-failure
  mysql-db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: job_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - mysql-db:/var/lib/mysql
    restart: on-failure

  recruitmentapp:
    image: recruitmentapp:latest
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://host.docker.internal:3306/job_db'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'Admin@123'
      SPRING_JPA_HIBERNATE_DDLAUTO: 'update'
      SPRING_DATA_REDIS_HOST: 'host.docker.internal'
      SPRING_DATA_REDIS_PORT: '6379'
      SPRING_DATA_REDIS_PASSWORD: 'Redis@123'
      SPRING_DATA_MONGODB_HOST: 'host.docker.internal'
      SPRING_DATA_MONGODB_PORT: '27017'
      SPRING_DATA_MONGODB_USERNAME: 'user'
      SPRING_DATA_MONGODB_PASSWORD: 'User123'
      SPRING_DATA_MONGODB_DATABASE: 'sample_db'
    ports:
      - '8080:8080'
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
volumes:
  grafana:
    driver: local
  mongodb:
    driver: local
  mysql-db:
    driver: local