version: '3.3'

services:
  redis:
    image: redis:7.2.1-alpine3.18
    environment:
      REDIS_PASSWORD: Redis@123
    ports:
      - '6379:6379'
    restart: on-failure
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD}"

  prometheus:
    image: prom/prometheus:v2.46.0
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana:10.0.3-ubuntu
    ports:
      - '3000:3000'
    volumes:
      - grafana:/var/lib/grafana
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana:
    driver: local