spring:
  application:
    name: RecruitmentApp
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8080
  servlet:
    session:
      timeout: 15m  # Set session timeout to 15 minutes

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_db?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
    show-sql: true
---
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: INFO
    org.springframework.security: DEBUG
    root: INFO
---
spring:
  cache:
    cache-names: USER
    type: redis
    redis:
      time-to-live: PT2M
  data:
    redis:
      host: localhost
      port: 6379
      password: Redis@123
---
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liS2v2Q8qL9JGOV2
            client-secret: 836b912edad638bccae7b40f11f59bab4385df70
            scope: read:user
            redirect-uri: "http://localhost:8080/login/oauth2/code/github"
            authorization-grant-type: authorization_code
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id








