spring:
  application:
    name: RecruitmentApp
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8080
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_db?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
    show-sql: true
---
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring:
  cache:
    cache-names: USER
    type: redis
    redis:
      time-to-live: PT2M
  data:
    redis:
      host: localhost
      port: 6379
      password: Redis@123
---





